version: '3.8'

networks:
  default:
    name: traefik-default

services:
  appdaemon:
    container_name: $COMPOSE_PROJECT_NAME
    image: acockburn/appdaemon:latest
    environment:
      - HA_URL=${HA_URL}
      - TOKEN=${HA_TOKEN}
      - DASH_URL=https://${DOMAIN}
    volumes:
      - ./volumes/conf:/conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=https"
      - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=5050"